apiVersion: v1
kind: ConfigMap
metadata:
  name: pesbuk-configmap
  namespace: staging
data:
  config.php: |
    <?php

    $db_host = "your database link";
    $db_user = "your database user";
    $db_pass = "your database pass";
    $db_name = "your database name";

    try {    
        //create PDO connection 
        $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
    } catch(PDOException $e) {
        //show error
        die("Terjadi masalah: " . $e->getMessage());
    }